// src/dummyEvents.js

const dummyEvents=[
    {
        id: 1,
		name: "Kerala Tech Conference 2024",
		venue: "Convention Center, Kochi",
		details: "A conference on the latest in tech.",
		maxCapacity: 500,
    },
    {
		id: 2,
		name: "Kochi Music Festival",
		venue: "Marine Drive, Kochi",
		details: "A weekend of music and fun.",
		maxCapacity: 1000,
	},
	{
		id: 3,
		name: "Trivandrum Art Exhibition",
		venue: "Art Gallery, Trivandrum",
		details: "Showcasing the best in modern art.",
		maxCapacity: 200,
	},
	{
		id: 4,
		name: "Kerala Book Fair",
		venue: "Exhibition Hall, Calicut",
		details: "A fair for book enthusiasts.",
		maxCapacity: 300,
	},{
		id: 5,
		name: "Kerala Food Festival",
		venue: "Subhash Park, Ernakulam",
		details: "A celebration of food and culture.",
		maxCapacity: 800,
	},
	{
		id: 6,
		name: "International Film Festival of Kerala",
		venue: "Tagore Theatre, Trivandrum",
		details: "Screening of independent films.",
		maxCapacity: 400,
	},
	{
		id: 7,
		name: "Kochi Startup Meetup",
		venue: "Infopark, Kochi",
		details: "Networking for startups and investors.",
		maxCapacity: 250,
	},
    {
		id: 8,
		name: "Kerala Gaming Convention",
		venue: "Convention Center, Trivandrum",
		details: "A convention for gaming enthusiasts.",
		maxCapacity: 600,
	},
	{
		id: 9,
		name: "Dance Workshop",
		venue: "Dance Studio, Thrissur",
		details: "Learn the latest dance moves.",
		maxCapacity: 150,
	},
	{
		id: 10,
		name: "Cochin Marathon",
		venue: "Marine Drive, Kochi",
		details: "A marathon for all age groups.",
		maxCapacity: 2000,
	},
	{
		id: 11,
		name: "Yoga Retreat",
		venue: "Beach Resort, Varkala",
		details: "A retreat to rejuvenate your mind and body.",
		maxCapacity: 100,
	},
	{
		id: 12,
		name: "Photography Workshop",
		venue: "Studio, Alleppey",
		details: "Learn the art of photography.",
		maxCapacity: 50,
	},
	{
		id: 13,
		name: "Coding Bootcamp",
		venue: "Tech Hub, Kochi",
		details: "An intensive coding bootcamp.",
		maxCapacity: 200,
	},
	{
		id: 14,
		name: "Fashion Show",
		venue: "Hotel Ballroom, Trivandrum",
		details: "A showcase of the latest fashion trends.",
		maxCapacity: 300,
	},
	{
		id: 15,
		name: "Health Expo",
		venue: "Expo Center, Kochi",
		details: "An expo on health and wellness.",
		maxCapacity: 700,
	},
	{
		id: 16,
		name: "Gardening Workshop",
		venue: "Community Center, Kollam",
		details: "Learn how to start your own garden.",
		maxCapacity: 50,
	},
	{
		id: 17,
		name: "Robotics Competition",
		venue: "University Hall, Cochin",
		details: "A competition for robotics enthusiasts.",
		maxCapacity: 400,
	},
	{
		id: 18,
		name: "Wine Tasting",
		venue: "Vineyard, Wayanad",
		details: "A tasting of the finest wines.",
		maxCapacity: 100,
	},
	{
		id: 19,
		name: "Meditation Session",
		venue: "Yoga Center, Munnar",
		details: "A session to meditate and relax.",
		maxCapacity: 100,
	},
	{
		id: 20,
		name: "Hiking Trip",
		venue: "Western Ghats, Idukki",
		details: "A trip for hiking enthusiasts.",
		maxCapacity: 60,
	},
];

export default dummyEvents;
